name: Coverage Report

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Backend setup
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      
      - name: Install backend dependencies
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install coverage pytest pytest-cov flask firebase-admin flask-cors
          pip install -r requirements.txt

      - name: Run backend tests with coverage
        working-directory: backend
        run: |
          python -m pytest --cov=src --cov-report=term-missing
          python -m coverage xml
          python -m coverage html

      # # Frontend setup
      # - name: Set up Node.js
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: '20.17.0'

      # - name: Install frontend dependencies
      #   run: |
      #     cd frontend
      #     npm install --force

      # - name: Run frontend tests with coverage
      #   run: |
      #     cd frontend
      #     npm test -- --coverage --coverageReporters=lcov  # Ensure correct report generation

      # Upload coverage reports to Codecov
      - name: Upload backend coverage report to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: ./backend/coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true

      # - name: Upload frontend coverage report to Codecov
      #   uses: codecov/codecov-action@v3
      #   env:
      #     CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      #   with:
      #     files: ./frontend/coverage/lcov.info  # Update based on actual path
      #     flags: unittests
      #     name: codecov-frontend
      #     fail_ci_if_error: true
      #     verbose: true

      # Archive code coverage results
      - name: Archive backend coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: |
            backend/coverage.xml
            backend/htmlcov

      # - name: Archive frontend coverage results
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: frontend-code-coverage-report
      #     path: frontend/coverage
